branches:
  except:
    - docs

language: ruby

cache:
  bundler: true
  directories:
    - node_modules
    - spec/rails4_dummy_app/node_modules

matrix:
  include:
    - rvm: 2.2.4
      gemfile: spec/rails4_dummy_app/Gemfile
      env: TEST_SUITE=rails4
    - rvm: 2.2.4
      gemfile: Gemfile
      env: TEST_SUITE=gem
    - rvm: 2.2.4
      env: TEST_SUITE=node

before_script:
  - nvm install 4.1
  - nvm use 4.1
  - npm install -g npm@^2.0
  - npm install -g webpack@^1.12.1
  - bundle exec rake setup:$TEST_SUITE
  - 'export CHROME_BIN=chromium-browser'
  - "export DISPLAY=:99.0" # Setup display for selenium driver
  - "sh -e /etc/init.d/xvfb start"
  - sleep 4 # give xvfb some time to start

script:
  - bundle exec rake test:$TEST_SUITE
